# Generated by Django 4.0.3 on 2022-03-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='voiture',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='nom',
            field=models.CharField(default=8, max_length=6),
            preserve_default=False,
        ),
    ]
