# Generated by Django 4.0.3 on 2022-05-06 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0005_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=6)),
                ('maintenanceDate', models.DateField(default=datetime.datetime(2022, 5, 6, 10, 0, 35, 537040))),
                ('mach', models.CharField(choices=[('directeur', 'directeur - en chef'), ('sous-directeur', 'sous-directeur - directeur en second'), ('ingénieure', 'ingénieure - s occupe de la maintenance des machine'), ('technicient', 'technicient - fait des machines')], default='PC', max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 6, 10, 0, 35, 536711)),
        ),
    ]
