# Generated by Django 4.0.3 on 2022-05-06 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0006_personne_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 6, 10, 4, 29, 529026)),
        ),
        migrations.AlterField(
            model_name='personne',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 6, 10, 4, 29, 529347)),
        ),
    ]
