# Generated by Django 4.0.3 on 2022-05-24 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0007_alter_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='perso_maint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computerApp.personne'),
        ),
        migrations.AddField(
            model_name='machine',
            name='ref',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('PC', 'PC - Windows'), ('Mac', 'MAc - MacOS'), ('Serveur', 'Serveur - Server to deploy virtual machines'), ('Switch', 'Switch - To maintains and connect servers')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 13, 48, 41, 865805)),
        ),
        migrations.AlterField(
            model_name='personne',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 13, 48, 41, 866284)),
        ),
    ]
