# Generated by Django 4.0.3 on 2022-05-24 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0008_machine_perso_maint_machine_ref_alter_machine_mach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 13, 57, 44, 877753)),
        ),
        migrations.AlterField(
            model_name='personne',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 13, 57, 44, 878198)),
        ),
    ]
